use_frameworks!

target 'SDCRelativeTimeIntervalFormatter_Example' do
  pod 'SDCRelativeTimeIntervalFormatter', :path => '../'

  target 'SDCRelativeTimeIntervalFormatter_Tests' do
    inherit! :search_paths

    
  end
end
